config/routes.rb
Rails.application.routes.draw do
  resources :categries

end

app/models/categry.rb
class Categry < ActiveRecord::Base
  has_many :products
  validates :name, presence: true
  before_validation do
    puts "Antes de la validacion"
  end
  after_validation do
    puts "Despues de la validacion"
  end
  before_save do
    puts "Antes de guardar"
  end
  after_save do
    puts "Despues de guardar"
  end
  after_initialize do
      if self.descrpcion.nil?
        self.descrpcion = 'No hay una descripcion disponible'
      end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :categry
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categries_controller.rb
class CategriesController < ApplicationController
  before_action :set_categry, only: [:show, :edit, :update, :destroy]
  before_action :valid_categry, only: [:show]

  # GET /categries
  # GET /categries.json
  def index
    @categries = Categry.all
  end

  # GET /categries/1
  # GET /categries/1.json
  def show
  end

  # GET /categries/new
  def new
    @categry = Categry.new
  end

  # GET /categries/1/edit
  def edit
  end

  # POST /categries
  # POST /categries.json
  def create
    @categry = Categry.new(categry_params)

    respond_to do |format|
      if @categry.save
        format.html { redirect_to @categry, notice: 'Categry was successfully created.' }
        format.json { render :show, status: :created, location: @categry }
      else
        format.html { render :new }
        format.json { render json: @categry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categries/1
  # PATCH/PUT /categries/1.json
  def update
    respond_to do |format|
      if @categry.update(categry_params)
        format.html { redirect_to @categry, notice: 'Categry was successfully updated.' }
        format.json { render :show, status: :ok, location: @categry }
      else
        format.html { render :edit }
        format.json { render json: @categry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categries/1
  # DELETE /categries/1.json
  def destroy
    @categry.destroy
    respond_to do |format|
      format.html { redirect_to categries_url, notice: 'Categry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categry
      @categry = Categry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categry_params
      params.require(:categry).permit(:name, :descrpcion, :price)
    end
  
  def valid_categry
    id = @categry.id
    valid = id < 8
    if !valid
      redirect_to categries_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categries_helper.rb
module CategriesHelper
end

app/views/categries/_form.html.erb
<%= form_for(@categry) do |f| %>
  <% if @categry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categry.errors.count, "error") %> prohibited this categry from being saved:</h2>

      <ul>
      <% @categry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :descrpcion %><br>
    <%= f.text_area :descrpcion %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categries/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @categry %> |
<%= link_to 'Back', categries_path %>

app/views/categries/index.html.erb
<h1>Categorias</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Descripcion</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categries.each do |categry| %>
      <tr>
        <td><%= categry.name %></td>
        <td><%= categry.descrpcion %></td>
        <td><%= categry.price %></td>
        <td><%= link_to 'Show', categry %></td>
        <td><%= link_to 'Edit', edit_categry_path(categry) %></td>
        <td><%= link_to 'Destroy', categry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_categry_path %>

app/views/categries/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categries_path %>

app/views/categries/product.html.erb
<h1>New product/h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/categries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @categry.name %>
</p>

<p>
  <strong>Descrpcion:</strong>
  <%= @categry.descrpcion %>
</p>

<p>
  <strong>Productos:</strong>
  <ul>
    <% @categry.products.each do |product| %>
    <li><%= product.name %></li>
    <% end %>
  </ul>
</p>

<p>
  <strong>Price:</strong>
  <%= @categry.price %>
</p>

<%= link_to 'Edit', edit_categry_path(@categry) %> |
<%= link_to 'Back', categries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catalogo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>